# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mixchat.ui'
##
## Created by: Qt User Interface Compiler version 6.9.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtQuickWidgets import QQuickWidget
from PySide6.QtWidgets import (QAbstractItemView, QAbstractScrollArea, QApplication, QFormLayout,
    QGridLayout, QGroupBox, QHBoxLayout, QHeaderView,
    QLabel, QLayout, QLineEdit, QListView,
    QListWidget, QListWidgetItem, QMainWindow, QMenu,
    QMenuBar, QPlainTextEdit, QPushButton, QSizePolicy,
    QSplitter, QStatusBar, QTabWidget, QToolBar,
    QToolButton, QTreeView, QVBoxLayout, QWidget)
from . import resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowModality(Qt.WindowModality.NonModal)
        MainWindow.resize(668, 592)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet(u"QLineEdit:focus {\n"
"  /* override background on focused input to make it abundantly clear where the cursor is */\n"
"  background: rgb(173, 213, 251) !important;\n"
"}\n"
"\n"
"QToolBar :hover {\n"
"   /* active item in the toolbar */\n"
"   background-color: #8effc3 !important;\n"
"}\n"
"\n"
"QTreeView {\n"
"    show-decoration-selected: 1;\n"
"}\n"
"\n"
"QTreeView::item {\n"
"    /*border-top-color: transparent;\n"
"    border-bottom-color: transparent;*/\n"
"}\n"
"\n"
"QTreeView *::item:hover {\n"
"/*    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #e7effd, stop: 1 #cbdaf1);\n"
"    border: 1px solid #bfcde4;*/\n"
"}\n"
"\n"
"QTreeView::item:selected {\n"
"    border: 1px solid #567dbc;\n"
"}\n"
"\n"
"QTreeView::item:selected:active{\n"
" /*   background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #6ea1f1, stop: 1 #567dbc);*/\n"
"}\n"
"\n"
"QTreeView::item:selected:!active {\n"
" /*   background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #6b9be8, stop: 1 #577fbf);*/\n"
""
                        "}\n"
"QTreeView::branch {\n"
"/*        background: palette(base);\n"
"        border: 1px solid black;*/\n"
"}\n"
"QTreeView::branch * {\n"
"/*       border: 2px solid red;*/\n"
"}\n"
"\n"
"/*\n"
"QTreeView::branch:has-siblings:!adjoins-item {\n"
"        background: cyan;\n"
"}\n"
"\n"
"QTreeView::branch:has-siblings:adjoins-item {\n"
"        background: red;\n"
"}\n"
"\n"
"QTreeView#ChatLines::branch:!has-children:!has-siblings:adjoins-item {\n"
"        background: blue;\n"
"}\n"
"\n"
"QTreeView::branch:closed:has-children:has-siblings {\n"
"        background: pink;\n"
"}\n"
"\n"
"QTreeView::branch:has-children:!has-siblings:closed {\n"
"        background: gray;\n"
"}\n"
"\n"
"QTreeView::branch:open:has-children:has-siblings {\n"
"        background: magenta;\n"
"}\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings {\n"
"        background: green;\n"
"}\n"
"*/")
        MainWindow.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        MainWindow.setDocumentMode(False)
        MainWindow.setDockOptions(QMainWindow.DockOption.AllowTabbedDocks|QMainWindow.DockOption.AnimatedDocks)
        self.action_testme = QAction(MainWindow)
        self.action_testme.setObjectName(u"action_testme")
        icon = QIcon()
        icon.addFile(u"fugue-icons-3.5.6/icons/flask--arrow.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_testme.setIcon(icon)
        self.action_testme.setMenuRole(QAction.MenuRole.ApplicationSpecificRole)
        self.action_accept_invitation = QAction(MainWindow)
        self.action_accept_invitation.setObjectName(u"action_accept_invitation")
        icon1 = QIcon()
        icon1.addFile(u"resources/accept.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_accept_invitation.setIcon(icon1)
        font = QFont()
        font.setPointSize(9)
        font.setBold(True)
        self.action_accept_invitation.setFont(font)
        self.action_accept_invitation.setMenuRole(QAction.MenuRole.ApplicationSpecificRole)
        self.action_invite_contact = QAction(MainWindow)
        self.action_invite_contact.setObjectName(u"action_invite_contact")
        icon2 = QIcon()
        icon2.addFile(u"resources/invite.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_invite_contact.setIcon(icon2)
        font1 = QFont()
        font1.setBold(True)
        self.action_invite_contact.setFont(font1)
        self.action_invite_contact.setMenuRole(QAction.MenuRole.ApplicationSpecificRole)
        self.action_quit = QAction(MainWindow)
        self.action_quit.setObjectName(u"action_quit")
        icon3 = QIcon()
        icon3.addFile(u"resources/quit.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_quit.setIcon(icon3)
        self.action_quit.setFont(font1)
        self.action_quit.setMenuRole(QAction.MenuRole.QuitRole)
        self.action_new_conversation = QAction(MainWindow)
        self.action_new_conversation.setObjectName(u"action_new_conversation")
        icon4 = QIcon()
        icon4.addFile(u"resources/3-chat.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_new_conversation.setIcon(icon4)
        font2 = QFont()
        font2.setBold(True)
        font2.setStrikeOut(False)
        self.action_new_conversation.setFont(font2)
        self.action_new_conversation.setMenuRole(QAction.MenuRole.ApplicationSpecificRole)
        self.action_display_font = QAction(MainWindow)
        self.action_display_font.setObjectName(u"action_display_font")
        self.action_display_font.setEnabled(True)
        icon5 = QIcon()
        icon5.addFile(u"fugue-icons-3.5.6/icons/edit-small-caps.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_display_font.setIcon(icon5)
        self.action_display_language = QAction(MainWindow)
        self.action_display_language.setObjectName(u"action_display_language")
        self.action_display_language.setEnabled(False)
        icon6 = QIcon()
        icon6.addFile(u"fugue-icons-3.5.6/icons/edit-language.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_display_language.setIcon(icon6)
        self.action_theme = QAction(MainWindow)
        self.action_theme.setObjectName(u"action_theme")
        self.action_theme.setEnabled(False)
        icon7 = QIcon()
        icon7.addFile(u"fugue-icons-3.5.6/icons/contrast.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_theme.setIcon(icon7)
        self.actionDocumentation = QAction(MainWindow)
        self.actionDocumentation.setObjectName(u"actionDocumentation")
        self.actionDocumentation.setEnabled(False)
        icon8 = QIcon()
        icon8.addFile(u"resources/information.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionDocumentation.setIcon(icon8)
        self.actionDocumentation.setFont(font1)
        self.actionDocumentation.setMenuRole(QAction.MenuRole.NoRole)
        self.action_space = QAction(MainWindow)
        self.action_space.setObjectName(u"action_space")
        self.action_space.setMenuRole(QAction.MenuRole.ApplicationSpecificRole)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy1)
        self.centralwidget.setAutoFillBackground(True)
        self.gridLayout_4 = QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.splitter = QSplitter(self.centralwidget)
        self.splitter.setObjectName(u"splitter")
        font3 = QFont()
        font3.setPointSize(14)
        self.splitter.setFont(font3)
        self.splitter.setOrientation(Qt.Orientation.Horizontal)
        self.splitter.setHandleWidth(8)
        self.groupBox = QGroupBox(self.splitter)
        self.groupBox.setObjectName(u"groupBox")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy2)
        font4 = QFont()
        font4.setPointSize(11)
        font4.setBold(True)
        self.groupBox.setFont(font4)
        self.gridLayout_2 = QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.contactFilterLineEdit = QLineEdit(self.groupBox)
        self.contactFilterLineEdit.setObjectName(u"contactFilterLineEdit")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.contactFilterLineEdit.sizePolicy().hasHeightForWidth())
        self.contactFilterLineEdit.setSizePolicy(sizePolicy3)
        self.contactFilterLineEdit.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.contactFilterLineEdit.setAutoFillBackground(False)
        self.contactFilterLineEdit.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_2.addWidget(self.contactFilterLineEdit, 0, 0, 1, 1)

        self.contacts_treeWidget = QTreeView(self.groupBox)
        self.contacts_treeWidget.setObjectName(u"contacts_treeWidget")
        sizePolicy2.setHeightForWidth(self.contacts_treeWidget.sizePolicy().hasHeightForWidth())
        self.contacts_treeWidget.setSizePolicy(sizePolicy2)
        font5 = QFont()
        font5.setPointSize(13)
        self.contacts_treeWidget.setFont(font5)
        self.contacts_treeWidget.setStyleSheet(u"QTreeView::item:selected {\n"
"      background-color: #2ABf9E;\n"
"       /* qlineargradient(spread:reflect, x1:0.5, y1:0.5, x2:0.5, y2:1, stop:0.497436 rgba(42, 191, 158, 234), stop:0.882051 rgba(255, 255, 255, 208));*/\n"
"}\n"
"QTreeView::item {\n"
"    height: 1.6em;\n"
"    margin-top: 0.2em;\n"
"    margin-bottom: 0.2em;\n"
"    padding-left: 1em; padding-right: 1em;\n"
"    background-color: qlineargradient(spread:reflect, x1:0.5, y1:0.5, x2:0.5, y2:1, stop:0.497436 rgba(216, 216, 216, 234), stop:0.882051 rgba(255, 255, 255, 208));\n"
"\n"
"    /*margin-left: 1em; margin-right: 1em;*/\n"
"    qproperty-alignment: AlignCenter;\n"
"}")
        self.contacts_treeWidget.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.contacts_treeWidget.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.contacts_treeWidget.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)
        self.contacts_treeWidget.setProperty(u"showDropIndicator", False)
        self.contacts_treeWidget.setAlternatingRowColors(True)
        self.contacts_treeWidget.setTextElideMode(Qt.TextElideMode.ElideRight)
        self.contacts_treeWidget.setUpdateThreshold(500)
        self.contacts_treeWidget.setIndentation(20)
        self.contacts_treeWidget.setRootIsDecorated(False)
        self.contacts_treeWidget.setUniformRowHeights(True)
        self.contacts_treeWidget.setSortingEnabled(True)
        self.contacts_treeWidget.setWordWrap(True)
        self.contacts_treeWidget.setHeaderHidden(True)
        self.contacts_treeWidget.header().setDefaultSectionSize(36)

        self.gridLayout_2.addWidget(self.contacts_treeWidget, 1, 0, 1, 1)

        self.splitter.addWidget(self.groupBox)
        self.groupBox_1 = QGroupBox(self.splitter)
        self.groupBox_1.setObjectName(u"groupBox_1")
        self.groupBox_1.setFont(font4)
        self.gridLayout = QGridLayout(self.groupBox_1)
        self.gridLayout.setObjectName(u"gridLayout")
        self.chatTabs = QTabWidget(self.groupBox_1)
        self.chatTabs.setObjectName(u"chatTabs")
        self.chatTabs.setEnabled(True)
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.MinimumExpanding)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.chatTabs.sizePolicy().hasHeightForWidth())
        self.chatTabs.setSizePolicy(sizePolicy4)
        self.chatTabs.setMinimumSize(QSize(100, 300))
        self.chatTabs.setAutoFillBackground(True)
        self.chatTabs.setStyleSheet(u"QTabBar::tab:selected {\n"
"  /* selected tab */\n"
"  /*background-color: rgba(255,0,0,.5);*/\n"
"}	\n"
"/*\n"
"QTabWidget::pane > QWidget > QWidget > QFrame { /* The tab widget frame */\n"
"   /* border: 1em solid #02C7CB;*/\n"
"    /*min-width: 30%;*/\n"
"/*}*/")
        self.chatTabs.setTabPosition(QTabWidget.TabPosition.South)
        self.chatTabs.setTabShape(QTabWidget.TabShape.Triangular)
        self.chatTabs.setDocumentMode(True)
        self.chatTabs.setTabsClosable(True)
        self.chatTabs.setTabBarAutoHide(True)
        self.defaultcontext = QWidget()
        self.defaultcontext.setObjectName(u"defaultcontext")
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush)
        brush1 = QBrush(QColor(42, 191, 158, 255))
        brush1.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush1)
        brush2 = QBrush(QColor(88, 255, 218, 255))
        brush2.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Light, brush2)
        brush3 = QBrush(QColor(65, 223, 188, 255))
        brush3.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Midlight, brush3)
        brush4 = QBrush(QColor(21, 95, 79, 255))
        brush4.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Dark, brush4)
        brush5 = QBrush(QColor(28, 127, 105, 255))
        brush5.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Mid, brush5)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush)
        brush6 = QBrush(QColor(255, 255, 255, 255))
        brush6.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.BrightText, brush6)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush6)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush1)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Shadow, brush)
        brush7 = QBrush(QColor(148, 223, 206, 255))
        brush7.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.AlternateBase, brush7)
        brush8 = QBrush(QColor(255, 255, 220, 255))
        brush8.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ToolTipBase, brush8)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ToolTipText, brush)
        brush9 = QBrush(QColor(0, 0, 0, 127))
        brush9.setStyle(Qt.BrushStyle.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.PlaceholderText, brush9)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Accent, brush6)
#endif
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush1)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Light, brush2)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Midlight, brush3)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Dark, brush4)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Mid, brush5)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.BrightText, brush6)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush6)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush1)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Shadow, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.AlternateBase, brush7)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ToolTipBase, brush8)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.PlaceholderText, brush9)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Accent, brush6)
#endif
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush4)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Light, brush2)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Midlight, brush3)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Dark, brush4)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Mid, brush5)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Text, brush4)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.BrightText, brush6)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ButtonText, brush4)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Shadow, brush)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.AlternateBase, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ToolTipBase, brush8)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ToolTipText, brush)
        brush10 = QBrush(QColor(21, 95, 79, 127))
        brush10.setStyle(Qt.BrushStyle.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.PlaceholderText, brush10)
#endif
        brush11 = QBrush(QColor(55, 248, 205, 255))
        brush11.setStyle(Qt.BrushStyle.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Accent, brush11)
#endif
        self.defaultcontext.setPalette(palette)
        self.defaultcontext.setAutoFillBackground(True)
        self.verticalLayout_8 = QVBoxLayout(self.defaultcontext)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.mywidget = QWidget(self.defaultcontext)
        self.mywidget.setObjectName(u"mywidget")
        sizePolicy5 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy5.setHorizontalStretch(1)
        sizePolicy5.setVerticalStretch(1)
        sizePolicy5.setHeightForWidth(self.mywidget.sizePolicy().hasHeightForWidth())
        self.mywidget.setSizePolicy(sizePolicy5)
        self.mywidget.setAutoFillBackground(True)
        self.gridLayout_3 = QGridLayout(self.mywidget)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.ContactName = QLabel(self.mywidget)
        self.ContactName.setObjectName(u"ContactName")
        sizePolicy6 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Preferred)
        sizePolicy6.setHorizontalStretch(0)
        sizePolicy6.setVerticalStretch(0)
        sizePolicy6.setHeightForWidth(self.ContactName.sizePolicy().hasHeightForWidth())
        self.ContactName.setSizePolicy(sizePolicy6)
        font6 = QFont()
        font6.setPointSize(12)
        font6.setBold(True)
        self.ContactName.setFont(font6)
        self.ContactName.setScaledContents(False)
        self.ContactName.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.ContactName.setWordWrap(True)
        self.ContactName.setMargin(10)

        self.gridLayout_3.addWidget(self.ContactName, 0, 0, 1, 1)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setSpacing(80)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.invite_contact_toolButton = QToolButton(self.mywidget)
        self.invite_contact_toolButton.setObjectName(u"invite_contact_toolButton")
        self.invite_contact_toolButton.setFont(font1)
        self.invite_contact_toolButton.setStyleSheet(u"\n"
"QToolButton:hover:!pressed\n"
"{\n"
"  background-color: #8effc3\n"
"}\n"
"\n"
"QToolButton {\n"
"    background-color: #d2ecf8;\n"
"}")
        self.invite_contact_toolButton.setIcon(icon2)
        self.invite_contact_toolButton.setIconSize(QSize(25, 25))
        self.invite_contact_toolButton.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextBesideIcon)

        self.horizontalLayout.addWidget(self.invite_contact_toolButton)

        self.search_in_chat = QLineEdit(self.mywidget)
        self.search_in_chat.setObjectName(u"search_in_chat")
        self.search_in_chat.setEnabled(False)

        self.horizontalLayout.addWidget(self.search_in_chat)


        self.gridLayout_3.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setSizeConstraint(QLayout.SizeConstraint.SetNoConstraint)

        self.gridLayout_3.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)

        self.singlemultitab = QTabWidget(self.mywidget)
        self.singlemultitab.setObjectName(u"singlemultitab")
        self.singlemultitab.setEnabled(True)
        sizePolicy7 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        sizePolicy7.setHorizontalStretch(0)
        sizePolicy7.setVerticalStretch(48)
        sizePolicy7.setHeightForWidth(self.singlemultitab.sizePolicy().hasHeightForWidth())
        self.singlemultitab.setSizePolicy(sizePolicy7)
        self.singlemultitab.setMinimumSize(QSize(0, 0))
        self.singlemultitab.setTabPosition(QTabWidget.TabPosition.South)
        self.singlemultitab.setTabShape(QTabWidget.TabShape.Rounded)
        self.singleline_tab = QWidget()
        self.singleline_tab.setObjectName(u"singleline_tab")
        sizePolicy8 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        sizePolicy8.setHorizontalStretch(0)
        sizePolicy8.setVerticalStretch(0)
        sizePolicy8.setHeightForWidth(self.singleline_tab.sizePolicy().hasHeightForWidth())
        self.singleline_tab.setSizePolicy(sizePolicy8)
        palette1 = QPalette()
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush)
        brush12 = QBrush(QColor(239, 239, 239, 255))
        brush12.setStyle(Qt.BrushStyle.SolidPattern)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush12)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Light, brush6)
        brush13 = QBrush(QColor(247, 247, 247, 255))
        brush13.setStyle(Qt.BrushStyle.SolidPattern)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Midlight, brush13)
        brush14 = QBrush(QColor(119, 119, 119, 255))
        brush14.setStyle(Qt.BrushStyle.SolidPattern)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Dark, brush14)
        brush15 = QBrush(QColor(159, 159, 159, 255))
        brush15.setStyle(Qt.BrushStyle.SolidPattern)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Mid, brush15)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.BrightText, brush6)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush6)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush12)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Shadow, brush)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.AlternateBase, brush13)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ToolTipBase, brush8)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.PlaceholderText, brush9)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Accent, brush6)
#endif
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush12)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Light, brush6)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Midlight, brush13)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Dark, brush14)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Mid, brush15)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.BrightText, brush6)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush6)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush12)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Shadow, brush)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.AlternateBase, brush13)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ToolTipBase, brush8)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.PlaceholderText, brush9)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Accent, brush6)
#endif
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush14)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush12)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Light, brush6)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Midlight, brush13)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Dark, brush14)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Mid, brush15)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Text, brush14)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.BrightText, brush6)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ButtonText, brush14)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush12)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush12)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Shadow, brush)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.AlternateBase, brush12)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ToolTipBase, brush8)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ToolTipText, brush)
        brush16 = QBrush(QColor(119, 119, 119, 127))
        brush16.setStyle(Qt.BrushStyle.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.PlaceholderText, brush16)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Accent, brush6)
#endif
        self.singleline_tab.setPalette(palette1)
        self.singleline_tab.setAutoFillBackground(True)
        self.verticalLayout_9 = QVBoxLayout(self.singleline_tab)
        self.verticalLayout_9.setObjectName(u"verticalLayout_9")
        self.chat_lineEdit = QLineEdit(self.singleline_tab)
        self.chat_lineEdit.setObjectName(u"chat_lineEdit")
        sizePolicy9 = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Fixed)
        sizePolicy9.setHorizontalStretch(0)
        sizePolicy9.setVerticalStretch(0)
        sizePolicy9.setHeightForWidth(self.chat_lineEdit.sizePolicy().hasHeightForWidth())
        self.chat_lineEdit.setSizePolicy(sizePolicy9)
        palette2 = QPalette()
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush12)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Light, brush6)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Midlight, brush13)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Dark, brush14)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Mid, brush15)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.BrightText, brush6)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush6)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush12)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Shadow, brush)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.AlternateBase, brush13)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ToolTipBase, brush8)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.PlaceholderText, brush9)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Accent, brush6)
#endif
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush12)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Light, brush6)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Midlight, brush13)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Dark, brush14)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Mid, brush15)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.BrightText, brush6)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush6)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush12)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Shadow, brush)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.AlternateBase, brush13)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ToolTipBase, brush8)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.PlaceholderText, brush9)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Accent, brush6)
#endif
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush14)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush12)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Light, brush6)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Midlight, brush13)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Dark, brush14)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Mid, brush15)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Text, brush14)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.BrightText, brush6)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ButtonText, brush14)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush12)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush12)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Shadow, brush)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.AlternateBase, brush12)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ToolTipBase, brush8)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.PlaceholderText, brush16)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Accent, brush6)
#endif
        self.chat_lineEdit.setPalette(palette2)
        self.chat_lineEdit.setAutoFillBackground(False)
        self.chat_lineEdit.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)

        self.verticalLayout_9.addWidget(self.chat_lineEdit)

        self.singlemultitab.addTab(self.singleline_tab, "")
        self.attach_file_tab = QWidget()
        self.attach_file_tab.setObjectName(u"attach_file_tab")
        self.attach_file_tab.setEnabled(False)
        self.attach_file_tab.setFont(font3)
        self.gridLayout_5 = QGridLayout(self.attach_file_tab)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.formLayout_2 = QFormLayout()
        self.formLayout_2.setObjectName(u"formLayout_2")
        self.formLayout_2.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.formLayout_2.setFieldGrowthPolicy(QFormLayout.FieldGrowthPolicy.FieldsStayAtSizeHint)
        self.formLayout_2.setRowWrapPolicy(QFormLayout.RowWrapPolicy.WrapAllRows)
        self.formLayout_2.setLabelAlignment(Qt.AlignmentFlag.AlignCenter)
        self.formLayout_2.setFormAlignment(Qt.AlignmentFlag.AlignBottom|Qt.AlignmentFlag.AlignHCenter)
        self.send_file_button = QToolButton(self.attach_file_tab)
        self.send_file_button.setObjectName(u"send_file_button")
        self.send_file_button.setEnabled(False)
        font7 = QFont()
        font7.setPointSize(10)
        self.send_file_button.setFont(font7)
        self.send_file_button.setAutoFillBackground(True)
        icon9 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.MailSend))
        self.send_file_button.setIcon(icon9)
        self.send_file_button.setAutoExclusive(True)
        self.send_file_button.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextUnderIcon)

        self.formLayout_2.setWidget(1, QFormLayout.ItemRole.LabelRole, self.send_file_button)

        self.attach_file_button = QToolButton(self.attach_file_tab)
        self.attach_file_button.setObjectName(u"attach_file_button")
        self.attach_file_button.setEnabled(False)
        self.attach_file_button.setFont(font7)
        self.attach_file_button.setAutoFillBackground(True)
        icon10 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentOpen))
        self.attach_file_button.setIcon(icon10)

        self.formLayout_2.setWidget(0, QFormLayout.ItemRole.FieldRole, self.attach_file_button)


        self.horizontalLayout_4.addLayout(self.formLayout_2)

        self.attached_files_QListWidget = QListWidget(self.attach_file_tab)
        self.attached_files_QListWidget.setObjectName(u"attached_files_QListWidget")
        self.attached_files_QListWidget.setEnabled(False)
        sizePolicy10 = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Ignored)
        sizePolicy10.setHorizontalStretch(0)
        sizePolicy10.setVerticalStretch(0)
        sizePolicy10.setHeightForWidth(self.attached_files_QListWidget.sizePolicy().hasHeightForWidth())
        self.attached_files_QListWidget.setSizePolicy(sizePolicy10)
        self.attached_files_QListWidget.setMinimumSize(QSize(0, 50))
        self.attached_files_QListWidget.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        self.attached_files_QListWidget.setAcceptDrops(True)
        self.attached_files_QListWidget.setAutoFillBackground(True)
        self.attached_files_QListWidget.setStyleSheet(u"QListWidget::item {\n"
"   /* margin-top: 0.5em; */\n"
"}")
        self.attached_files_QListWidget.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)
        self.attached_files_QListWidget.setProperty(u"showDropIndicator", False)
        self.attached_files_QListWidget.setDefaultDropAction(Qt.DropAction.ActionMask)
        self.attached_files_QListWidget.setAlternatingRowColors(True)
        self.attached_files_QListWidget.setSelectionMode(QAbstractItemView.SelectionMode.NoSelection)
        self.attached_files_QListWidget.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        self.attached_files_QListWidget.setVerticalScrollMode(QAbstractItemView.ScrollMode.ScrollPerPixel)
        self.attached_files_QListWidget.setHorizontalScrollMode(QAbstractItemView.ScrollMode.ScrollPerPixel)
        self.attached_files_QListWidget.setResizeMode(QListView.ResizeMode.Adjust)
        self.attached_files_QListWidget.setLayoutMode(QListView.LayoutMode.Batched)
        self.attached_files_QListWidget.setViewMode(QListView.ViewMode.IconMode)
        self.attached_files_QListWidget.setWordWrap(True)
        self.attached_files_QListWidget.setItemAlignment(Qt.AlignmentFlag.AlignCenter)
        self.attached_files_QListWidget.setSortingEnabled(True)

        self.horizontalLayout_4.addWidget(self.attached_files_QListWidget)


        self.gridLayout_5.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)

        self.singlemultitab.addTab(self.attach_file_tab, "")
        self.multilinetab = QWidget()
        self.multilinetab.setObjectName(u"multilinetab")
        sizePolicy8.setHeightForWidth(self.multilinetab.sizePolicy().hasHeightForWidth())
        self.multilinetab.setSizePolicy(sizePolicy8)
        self.multilinetab.setAutoFillBackground(True)
        self.gridLayout_6 = QGridLayout(self.multilinetab)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.chatInput = QPlainTextEdit(self.multilinetab)
        self.chatInput.setObjectName(u"chatInput")
        self.chatInput.setEnabled(False)
        sizePolicy11 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Preferred)
        sizePolicy11.setHorizontalStretch(0)
        sizePolicy11.setVerticalStretch(0)
        sizePolicy11.setHeightForWidth(self.chatInput.sizePolicy().hasHeightForWidth())
        self.chatInput.setSizePolicy(sizePolicy11)
        self.chatInput.setAutoFillBackground(True)
        self.chatInput.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.chatInput.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.chatInput.setTextInteractionFlags(Qt.TextInteractionFlag.NoTextInteraction)

        self.gridLayout_6.addWidget(self.chatInput, 0, 1, 1, 1)

        self.pushButton_3 = QPushButton(self.multilinetab)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setEnabled(False)
        sizePolicy12 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy12.setHorizontalStretch(0)
        sizePolicy12.setVerticalStretch(0)
        sizePolicy12.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy12)
        self.pushButton_3.setFont(font7)
        self.pushButton_3.setAutoFillBackground(True)

        self.gridLayout_6.addWidget(self.pushButton_3, 0, 0, 1, 1)

        self.singlemultitab.addTab(self.multilinetab, "")
        self.ptt_tab = QWidget()
        self.ptt_tab.setObjectName(u"ptt_tab")
        self.ptt_tab.setEnabled(False)
        self.gridLayout_7 = QGridLayout(self.ptt_tab)
        self.gridLayout_7.setObjectName(u"gridLayout_7")
        self.ptt_cancel = QLabel(self.ptt_tab)
        self.ptt_cancel.setObjectName(u"ptt_cancel")
        self.ptt_cancel.setTextFormat(Qt.TextFormat.MarkdownText)
        self.ptt_cancel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.ptt_cancel.setTextInteractionFlags(Qt.TextInteractionFlag.NoTextInteraction)

        self.gridLayout_7.addWidget(self.ptt_cancel, 0, 0, 1, 1)

        self.ptt_hold_space_label = QLabel(self.ptt_tab)
        self.ptt_hold_space_label.setObjectName(u"ptt_hold_space_label")
        self.ptt_hold_space_label.setEnabled(False)
        self.ptt_hold_space_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.gridLayout_7.addWidget(self.ptt_hold_space_label, 1, 0, 1, 1)

        icon11 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.MediaRecord))
        self.singlemultitab.addTab(self.ptt_tab, icon11, "")

        self.gridLayout_3.addWidget(self.singlemultitab, 4, 0, 1, 1)

        self.qml_ChatLines = QQuickWidget(self.mywidget)
        self.qml_ChatLines.setObjectName(u"qml_ChatLines")
        sizePolicy1.setHeightForWidth(self.qml_ChatLines.sizePolicy().hasHeightForWidth())
        self.qml_ChatLines.setSizePolicy(sizePolicy1)
        self.qml_ChatLines.setAcceptDrops(False)
        self.qml_ChatLines.setAutoFillBackground(True)
        self.qml_ChatLines.setResizeMode(QQuickWidget.ResizeMode.SizeRootObjectToView)

        self.gridLayout_3.addWidget(self.qml_ChatLines, 3, 0, 1, 1)


        self.verticalLayout_8.addWidget(self.mywidget)

        self.chatTabs.addTab(self.defaultcontext, "")

        self.gridLayout.addWidget(self.chatTabs, 0, 0, 1, 1)

        self.splitter.addWidget(self.groupBox_1)

        self.gridLayout_4.addWidget(self.splitter, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 668, 20))
        self.menubar.setMinimumSize(QSize(0, 20))
        self.menuSettings = QMenu(self.menubar)
        self.menuSettings.setObjectName(u"menuSettings")
        self.menuMixnetStatus = QMenu(self.menubar)
        self.menuMixnetStatus.setObjectName(u"menuMixnetStatus")
        self.menuMixnetStatus.setEnabled(False)
        self.menuAbout = QMenu(self.menubar)
        self.menuAbout.setObjectName(u"menuAbout")
        self.menuAbout.setEnabled(False)
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        self.toolBar.setEnabled(True)
        sizePolicy13 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Minimum)
        sizePolicy13.setHorizontalStretch(0)
        sizePolicy13.setVerticalStretch(0)
        sizePolicy13.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy13)
        self.toolBar.setMinimumSize(QSize(0, 0))
        self.toolBar.setMaximumSize(QSize(16777215, 40))
        palette3 = QPalette()
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush)
        brush17 = QBrush(QColor(185, 225, 255, 255))
        brush17.setStyle(Qt.BrushStyle.SolidPattern)
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush17)
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Light, brush6)
        brush18 = QBrush(QColor(220, 240, 255, 255))
        brush18.setStyle(Qt.BrushStyle.SolidPattern)
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Midlight, brush18)
        brush19 = QBrush(QColor(92, 113, 127, 255))
        brush19.setStyle(Qt.BrushStyle.SolidPattern)
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Dark, brush19)
        brush20 = QBrush(QColor(123, 150, 170, 255))
        brush20.setStyle(Qt.BrushStyle.SolidPattern)
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Mid, brush20)
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush)
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.BrightText, brush6)
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush)
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush6)
        brush21 = QBrush(QColor(206, 231, 243, 255))
        brush21.setStyle(Qt.BrushStyle.SolidPattern)
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush21)
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Shadow, brush)
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.AlternateBase, brush18)
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ToolTipBase, brush8)
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.PlaceholderText, brush9)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Accent, brush6)
#endif
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush17)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Light, brush6)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Midlight, brush18)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Dark, brush19)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Mid, brush20)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.BrightText, brush6)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush6)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush21)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Shadow, brush)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.AlternateBase, brush18)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ToolTipBase, brush8)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.PlaceholderText, brush9)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Accent, brush6)
#endif
        palette3.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush19)
        palette3.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush17)
        palette3.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Light, brush6)
        palette3.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Midlight, brush18)
        palette3.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Dark, brush19)
        palette3.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Mid, brush20)
        palette3.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Text, brush19)
        palette3.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.BrightText, brush6)
        palette3.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ButtonText, brush19)
        palette3.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush21)
        palette3.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush21)
        palette3.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Shadow, brush)
        palette3.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.AlternateBase, brush17)
        palette3.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ToolTipBase, brush8)
        palette3.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ToolTipText, brush)
        brush22 = QBrush(QColor(92, 113, 127, 127))
        brush22.setStyle(Qt.BrushStyle.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.PlaceholderText, brush22)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette3.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Accent, brush6)
#endif
        self.toolBar.setPalette(palette3)
        self.toolBar.setFont(font1)
        self.toolBar.setContextMenuPolicy(Qt.ContextMenuPolicy.PreventContextMenu)
        self.toolBar.setAutoFillBackground(True)
        self.toolBar.setMovable(True)
        self.toolBar.setOrientation(Qt.Orientation.Horizontal)
        self.toolBar.setIconSize(QSize(27, 27))
        self.toolBar.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuMixnetStatus.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.menuSettings.addAction(self.action_display_font)
        self.menuSettings.addAction(self.action_display_language)
        self.menuSettings.addAction(self.action_theme)
        self.toolBar.addAction(self.action_new_conversation)
        self.toolBar.addAction(self.action_accept_invitation)
        self.toolBar.addAction(self.actionDocumentation)
        self.toolBar.addAction(self.action_quit)
        self.toolBar.addAction(self.action_testme)

        self.retranslateUi(MainWindow)
        self.invite_contact_toolButton.clicked.connect(self.action_invite_contact.trigger)

        self.chatTabs.setCurrentIndex(0)
        self.singlemultitab.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
#if QT_CONFIG(statustip)
        MainWindow.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.action_testme.setText(QCoreApplication.translate("MainWindow", u"Testme", None))
        self.action_testme.setIconText(QCoreApplication.translate("MainWindow", u" Testme", None))
#if QT_CONFIG(tooltip)
        self.action_testme.setToolTip(QCoreApplication.translate("MainWindow", u"I am going away", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.action_testme.setStatusTip(QCoreApplication.translate("MainWindow", u"Accept invitation received from contact", None))
#endif // QT_CONFIG(statustip)
        self.action_accept_invitation.setText(QCoreApplication.translate("MainWindow", u"Accept invitation", None))
        self.action_accept_invitation.setIconText(QCoreApplication.translate("MainWindow", u" Accept invitation   ", None))
#if QT_CONFIG(tooltip)
        self.action_accept_invitation.setToolTip(QCoreApplication.translate("MainWindow", u"Accept invitation received from contact", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.action_accept_invitation.setStatusTip(QCoreApplication.translate("MainWindow", u"Accept invitation received from contact", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.action_accept_invitation.setWhatsThis(QCoreApplication.translate("MainWindow", u"TODO-acceptinvitation", None))
#endif // QT_CONFIG(whatsthis)
        self.action_invite_contact.setText(QCoreApplication.translate("MainWindow", u"Invite contact", None))
        self.action_invite_contact.setIconText(QCoreApplication.translate("MainWindow", u" Invite contact   ", None))
#if QT_CONFIG(tooltip)
        self.action_invite_contact.setToolTip(QCoreApplication.translate("MainWindow", u"Generate a new invitation that can be passed on to a contact", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.action_invite_contact.setStatusTip(QCoreApplication.translate("MainWindow", u"Generate a new invitation that can be passed on to a contact", None))
#endif // QT_CONFIG(statustip)
        self.action_quit.setText(QCoreApplication.translate("MainWindow", u"Quit", None))
        self.action_quit.setIconText(QCoreApplication.translate("MainWindow", u" Quit       ", None))
#if QT_CONFIG(tooltip)
        self.action_quit.setToolTip(QCoreApplication.translate("MainWindow", u"Quit the application", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.action_quit.setStatusTip(QCoreApplication.translate("MainWindow", u"Quit the application", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.action_quit.setWhatsThis(QCoreApplication.translate("MainWindow", u"TODO-quit", None))
#endif // QT_CONFIG(whatsthis)
        self.action_new_conversation.setText(QCoreApplication.translate("MainWindow", u"New conversation", None))
        self.action_new_conversation.setIconText(QCoreApplication.translate("MainWindow", u" New conversation   ", None))
#if QT_CONFIG(whatsthis)
        self.action_new_conversation.setWhatsThis(QCoreApplication.translate("MainWindow", u"TODO-newconversation", None))
#endif // QT_CONFIG(whatsthis)
        self.action_display_font.setText(QCoreApplication.translate("MainWindow", u"Display font", None))
#if QT_CONFIG(whatsthis)
        self.action_display_font.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.action_display_language.setText(QCoreApplication.translate("MainWindow", u"Display language", None))
#if QT_CONFIG(tooltip)
        self.action_display_language.setToolTip(QCoreApplication.translate("MainWindow", u"Display language", None))
#endif // QT_CONFIG(tooltip)
        self.action_theme.setText(QCoreApplication.translate("MainWindow", u"Theme", None))
        self.actionDocumentation.setText(QCoreApplication.translate("MainWindow", u"Documentation", None))
        self.actionDocumentation.setIconText(QCoreApplication.translate("MainWindow", u" Documentation   ", None))
#if QT_CONFIG(tooltip)
        self.actionDocumentation.setToolTip(QCoreApplication.translate("MainWindow", u"Quick help for users", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.actionDocumentation.setWhatsThis(QCoreApplication.translate("MainWindow", u"TODO-documentation", None))
#endif // QT_CONFIG(whatsthis)
        self.action_space.setText(QCoreApplication.translate("MainWindow", u"space", None))
#if QT_CONFIG(shortcut)
        self.action_space.setShortcut(QCoreApplication.translate("MainWindow", u"Space", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(whatsthis)
        self.groupBox.setWhatsThis(QCoreApplication.translate("MainWindow", u"TODO-convosandcontacts", None))
#endif // QT_CONFIG(whatsthis)
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Conversations and contacts", None))
#if QT_CONFIG(statustip)
        self.contactFilterLineEdit.setStatusTip(QCoreApplication.translate("MainWindow", u"Type to filter contacts.", None))
#endif // QT_CONFIG(statustip)
        self.contactFilterLineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Type to filter contacts...", None))
#if QT_CONFIG(whatsthis)
        self.groupBox_1.setWhatsThis(QCoreApplication.translate("MainWindow", u"TODO-messages", None))
#endif // QT_CONFIG(whatsthis)
        self.groupBox_1.setTitle(QCoreApplication.translate("MainWindow", u"Messages", None))
#if QT_CONFIG(whatsthis)
        self.chatTabs.setWhatsThis(QCoreApplication.translate("MainWindow", u"Tabs with active chats", None))
#endif // QT_CONFIG(whatsthis)
        self.ContactName.setText(QCoreApplication.translate("MainWindow", u"You have no conversations yet. Click \"New conversation\" to get started.", None))
#if QT_CONFIG(tooltip)
        self.invite_contact_toolButton.setToolTip(QCoreApplication.translate("MainWindow", u"Generate an invitation code for this conversation", None))
#endif // QT_CONFIG(tooltip)
        self.invite_contact_toolButton.setText(QCoreApplication.translate("MainWindow", u"  Invite a contact", None))
#if QT_CONFIG(tooltip)
        self.search_in_chat.setToolTip(QCoreApplication.translate("MainWindow", u"Search the messages for keywords", None))
#endif // QT_CONFIG(tooltip)
        self.search_in_chat.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Search in chat...(TODO)", None))
#if QT_CONFIG(statustip)
        self.chat_lineEdit.setStatusTip(QCoreApplication.translate("MainWindow", u"Type a message. Press Enter when done.", None))
#endif // QT_CONFIG(statustip)
        self.chat_lineEdit.setText("")
        self.chat_lineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Single-line message", None))
        self.singlemultitab.setTabText(self.singlemultitab.indexOf(self.singleline_tab), QCoreApplication.translate("MainWindow", u"Single-line", None))
#if QT_CONFIG(tooltip)
        self.singlemultitab.setTabToolTip(self.singlemultitab.indexOf(self.singleline_tab), QCoreApplication.translate("MainWindow", u"Type a message in a single-line input field. The message length can be longer than what is visible.", None))
#endif // QT_CONFIG(tooltip)
        self.send_file_button.setText(QCoreApplication.translate("MainWindow", u"&Send!", None))
#if QT_CONFIG(shortcut)
        self.send_file_button.setShortcut(QCoreApplication.translate("MainWindow", u"S", None))
#endif // QT_CONFIG(shortcut)
        self.attach_file_button.setText(QCoreApplication.translate("MainWindow", u"&Attach file(s)", None))
#if QT_CONFIG(shortcut)
        self.attach_file_button.setShortcut(QCoreApplication.translate("MainWindow", u"A", None))
#endif // QT_CONFIG(shortcut)
        self.singlemultitab.setTabText(self.singlemultitab.indexOf(self.attach_file_tab), QCoreApplication.translate("MainWindow", u"Send file", None))
#if QT_CONFIG(tooltip)
        self.singlemultitab.setTabToolTip(self.singlemultitab.indexOf(self.attach_file_tab), QCoreApplication.translate("MainWindow", u"Send a file to contacts in this conversation", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.chatInput.setStatusTip(QCoreApplication.translate("MainWindow", u"Multi-line message entry", None))
#endif // QT_CONFIG(statustip)
        self.chatInput.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Multi-line message", None))
#if QT_CONFIG(statustip)
        self.pushButton_3.setStatusTip(QCoreApplication.translate("MainWindow", u"Send message to the chat", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.pushButton_3.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"Send!", None))
        self.singlemultitab.setTabText(self.singlemultitab.indexOf(self.multilinetab), QCoreApplication.translate("MainWindow", u"Multi-line", None))
#if QT_CONFIG(tooltip)
        self.singlemultitab.setTabToolTip(self.singlemultitab.indexOf(self.multilinetab), QCoreApplication.translate("MainWindow", u"Type a message in a multi-line entry field for easier editing", None))
#endif // QT_CONFIG(tooltip)
        self.ptt_cancel.setText(QCoreApplication.translate("MainWindow", u"**TODO**: *ToolButton to cancel in-progress recording*", None))
        self.ptt_hold_space_label.setText(QCoreApplication.translate("MainWindow", u"Hold space bar to record audio.", None))
        self.singlemultitab.setTabText(self.singlemultitab.indexOf(self.ptt_tab), QCoreApplication.translate("MainWindow", u"&Push to talk (voice)", None))
#if QT_CONFIG(tooltip)
        self.singlemultitab.setTabToolTip(self.singlemultitab.indexOf(self.ptt_tab), QCoreApplication.translate("MainWindow", u"Send a voice message to the current conversation", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.qml_ChatLines.setStatusTip(QCoreApplication.translate("MainWindow", u"chat history lines QML", None))
#endif // QT_CONFIG(statustip)
        self.chatTabs.setTabText(self.chatTabs.indexOf(self.defaultcontext), QCoreApplication.translate("MainWindow", u"Contact1", None))
        self.menuSettings.setTitle(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.menuMixnetStatus.setTitle(QCoreApplication.translate("MainWindow", u"Mixnet status", None))
        self.menuAbout.setTitle(QCoreApplication.translate("MainWindow", u"About", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
#if QT_CONFIG(whatsthis)
        self.toolBar.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
    # retranslateUi

