"""Make first_unread an int instead

Revision ID: 1422bffc8e28
Revises: aa38593d6084
Create Date: 2025-09-11 20:48:19.521200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1422bffc8e28'
down_revision: Union[str, Sequence[str], None] = 'aa38593d6084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.alter_column('first_unread',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('conversation_first_unread_fk'), type_='foreignkey')

    with op.batch_alter_table('mixwal', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_mixwal_bacap_stream'), ['bacap_stream'])
        batch_op.create_unique_constraint(batch_op.f('uq_mixwal_envelope_hash'), ['envelope_hash'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mixwal', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_mixwal_envelope_hash'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_mixwal_bacap_stream'), type_='unique')

    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('conversation_first_unread_fk'), 'conversationlog', ['first_unread'], ['id'])
        batch_op.alter_column('first_unread',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=True)

    # ### end Alembic commands ###
