"""store envelope_descriptor in MixWAL

Revision ID: 5856f0a24fc9
Revises: 7094a18467be
Create Date: 2025-09-21 23:17:30.435101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5856f0a24fc9'
down_revision: Union[str, Sequence[str], None] = '7094a18467be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mixwal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('envelope_descriptor', sa.LargeBinary(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mixwal', schema=None) as batch_op:
        batch_op.drop_column('envelope_descriptor')

    # ### end Alembic commands ###
