"""x

Revision ID: 6108dd0ca841
Revises: 
Create Date: 2025-06-18 19:09:04.948571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6108dd0ca841'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversationpeer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('read_cap', sa.LargeBinary(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversationpeer_name'), 'conversationpeer', ['name'], unique=False)
    op.create_table('mixwal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('envelope_hash', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('own_peer_id', sa.Integer(), nullable=False),
    sa.Column('write_cap', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['own_peer_id'], ['conversationpeer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_name'), 'conversation', ['name'], unique=False)
    op.create_index(op.f('ix_conversation_own_peer_id'), 'conversation', ['own_peer_id'], unique=False)
    op.create_table('conversationlog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('conversation_peer_id', sa.Integer(), nullable=False),
    sa.Column('conversation_order', sa.Integer(), nullable=False),
    sa.Column('payload', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['conversation_peer_id'], ['conversationpeer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'conversation_order', name='uniq_conv_id_and_order')
    )
    op.create_index(op.f('ix_conversationlog_conversation_id'), 'conversationlog', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversationlog_conversation_order'), 'conversationlog', ['conversation_order'], unique=False)
    op.create_index(op.f('ix_conversationlog_conversation_peer_id'), 'conversationlog', ['conversation_peer_id'], unique=False)
    op.create_table('conversationpeerlink',
    sa.Column('conversation_peer_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['conversation_peer_id'], ['conversationpeer.id'], ),
    sa.PrimaryKeyConstraint('conversation_peer_id', 'conversation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversationpeerlink')
    op.drop_index(op.f('ix_conversationlog_conversation_peer_id'), table_name='conversationlog')
    op.drop_index(op.f('ix_conversationlog_conversation_order'), table_name='conversationlog')
    op.drop_index(op.f('ix_conversationlog_conversation_id'), table_name='conversationlog')
    op.drop_table('conversationlog')
    op.drop_index(op.f('ix_conversation_own_peer_id'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_name'), table_name='conversation')
    op.drop_table('conversation')
    op.drop_table('mixwal')
    op.drop_index(op.f('ix_conversationpeer_name'), table_name='conversationpeer')
    op.drop_table('conversationpeer')
    # ### end Alembic commands ###
