"""SQLite doesnt like 64bit integers

Revision ID: 93eef61c3c54
Revises: a430f7202849
Create Date: 2025-10-01 16:44:33.045587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '93eef61c3c54'
down_revision: Union[str, Sequence[str], None] = 'a430f7202849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receivedpiece', schema=None) as batch_op:
        batch_op.alter_column('bacap_index',
               existing_type=sa.INTEGER(),
               type_=sa.LargeBinary(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receivedpiece', schema=None) as batch_op:
        batch_op.alter_column('bacap_index',
               existing_type=sa.LargeBinary(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
