ARG BASE=docker.io/ubuntu:26.04
FROM ${BASE}

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update \
	&& apt install -y --no-install-recommends \
		python3 python3-dev python3-pip python3-venv \
		build-essential cargo rustc git ca-certificates unzip dpkg-dev libasound2-dev pkg-config \
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /build
