"""tally state

Revision ID: 0711d7a23cd9
Revises: ebaba8b49f83
Create Date: 2026-06-09 12:36:35.802500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0711d7a23cd9'
down_revision: Union[str, Sequence[str], None] = 'ebaba8b49f83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tallystate',
    sa.Column('survey_id', sa.LargeBinary(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('doc_state', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], name=op.f('fk_tallystate_conversation_id_conversation')),
    sa.PrimaryKeyConstraint('survey_id', name=op.f('pk_tallystate'))
    )
    with op.batch_alter_table('tallystate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tallystate_conversation_id'), ['conversation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tallystate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tallystate_conversation_id'))

    op.drop_table('tallystate')
    # ### end Alembic commands ###
