"""Indirection support in PlaintextWAL

Revision ID: 2363e8f1cb58
Revises: 6bc3434dc7d9
Create Date: 2025-09-26 18:07:00.823819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2363e8f1cb58'
down_revision: Union[str, Sequence[str], None] = '6bc3434dc7d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaintextwal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('indirection', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_plaintextwal_indirection'), ['indirection'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_plaintextwal_indirection_readcapwal'), 'readcapwal', ['indirection'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plaintextwal', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_plaintextwal_indirection_readcapwal'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_plaintextwal_indirection'))
        batch_op.drop_column('indirection')

    # ### end Alembic commands ###
