"""Stuff for tracking if we have sent a message

Revision ID: 524576e2f8a5
Revises: 2363e8f1cb58
Create Date: 2025-09-26 19:37:51.023401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '524576e2f8a5'
down_revision: Union[str, Sequence[str], None] = '2363e8f1cb58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversationlog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('network_status', sa.Integer(), nullable=False, default=0))
        batch_op.add_column(sa.Column('outgoing_pwal', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_conversationlog_outgoing_pwal'), ['outgoing_pwal'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_conversationlog_outgoing_pwal_plaintextwal'), 'plaintextwal', ['outgoing_pwal'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversationlog', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_conversationlog_outgoing_pwal_plaintextwal'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_conversationlog_outgoing_pwal'))
        batch_op.drop_column('outgoing_pwal')
        batch_op.drop_column('network_status')

    # ### end Alembic commands ###
