"""MixWAL: keep track of PlaintextWAL for writes

Revision ID: 5c851b1a68be
Revises: 5856f0a24fc9
Create Date: 2025-09-24 12:11:13.041633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5c851b1a68be'
down_revision: Union[str, Sequence[str], None] = '5856f0a24fc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mixwal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plaintextwal', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_mixwal_plaintextwal'), ['plaintextwal'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_mixwal_plaintextwal_plaintextwal'), 'plaintextwal', ['plaintextwal'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mixwal', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_mixwal_plaintextwal_plaintextwal'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_mixwal_plaintextwal'))
        batch_op.drop_column('plaintextwal')

    # ### end Alembic commands ###
