"""mixwal: current_message_index

Revision ID: 7094a18467be
Revises: 1422bffc8e28
Create Date: 2025-09-21 12:47:55.045998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7094a18467be'
down_revision: Union[str, Sequence[str], None] = '1422bffc8e28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mixwal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_message_index', sa.LargeBinary(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mixwal', schema=None) as batch_op:
        batch_op.drop_column('current_message_index')

    # ### end Alembic commands ###
