"""First go at ReceivedPiece

Revision ID: a430f7202849
Revises: 524576e2f8a5
Create Date: 2025-09-29 16:28:15.817234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a430f7202849'
down_revision: Union[str, Sequence[str], None] = '524576e2f8a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receivedpiece',
    sa.Column('read_cap', sa.Uuid(), nullable=False),
    sa.Column('bacap_index', sa.Integer(), nullable=False),
    sa.Column('chunk_type', sa.LargeBinary(), nullable=False),
    sa.Column('chunk', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['read_cap'], ['readcapwal.id'], name=op.f('fk_receivedpiece_read_cap_readcapwal')),
    sa.PrimaryKeyConstraint('read_cap', 'bacap_index', name=op.f('pk_receivedpiece'))
    )
    with op.batch_alter_table('receivedpiece', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receivedpiece_read_cap'), ['read_cap'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receivedpiece', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receivedpiece_read_cap'))

    op.drop_table('receivedpiece')
    # ### end Alembic commands ###
