"""Added first_unread to Conversation to keep track of conversation scroll state

Revision ID: aa38593d6084
Revises: 888b1ac7eca0
Create Date: 2025-09-11 20:23:30.507912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aa38593d6084'
down_revision: Union[str, Sequence[str], None] = '888b1ac7eca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_unread', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key("conversation_first_unread_fk", 'conversationlog', ['first_unread'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('first_unread')

    # ### end Alembic commands ###
