"""PendingVoucher table

Revision ID: ebaba8b49f83
Revises: f38b7d37f88a
Create Date: 2026-06-04 08:38:26.591405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ebaba8b49f83'
down_revision: Union[str, Sequence[str], None] = 'f38b7d37f88a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pendingvoucher',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('step', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('voucher', sa.LargeBinary(), nullable=False),
    sa.Column('voucher_write_cap', sa.LargeBinary(), nullable=True),
    sa.Column('voucher_read_cap', sa.LargeBinary(), nullable=True),
    sa.Column('voucher_secret_key', sa.LargeBinary(), nullable=True),
    sa.Column('box1_index', sa.LargeBinary(), nullable=True),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('peer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], name=op.f('fk_pendingvoucher_conversation_id_conversation')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pendingvoucher'))
    )
    with op.batch_alter_table('pendingvoucher', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pendingvoucher_conversation_id'), ['conversation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendingvoucher', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pendingvoucher_conversation_id'))

    op.drop_table('pendingvoucher')
    # ### end Alembic commands ###
